server:
  port: 8086 # Yeni servisimiz için yeni bir port
  servlet:
    context-path: /

spring:
  application:
    name: websocket-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Harita güncellemeleri için kullanılacak exchange ve queue isimleri
app:
  rabbitmq:
    exchange: "afet_exchange"
    queues:
      map-update: "map_update_queue"
    routing-keys:
      map-update: "map_update_routingKey"

# Logging konfigürasyonu
logging:
  level:
    com.afet.websocketservice: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka