server:
  port: 8085

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: "afet_exchange"
    queues:
      notification: "notification_queue"
    routing-keys:
      notification: "notification_routingKey"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka