spring:
  application:
    name: request-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/disastermanagement
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

app:
  rabbitmq:
    exchange: "afet_exchange"
    queues:
      notification: "notification_queue"
    routing-keys:
      map-update: map.update.key
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

