server:
  port: 8084

spring:
  application:
    name: information-service

  datasource:
    url: jdbc:postgresql://localhost:5432/disastermanagement
    username: root
    password: root


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


app:
  rabbitmq:
    exchange: "afet_exchange"
    queues:
      notification: "notification_queue"
    routing-keys:
      notification: "notification_routingKey"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka