version: '3.8'

services:
  # Development Frontend with hot reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: disaster-management-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - disaster-network
    restart: unless-stopped

networks:
  disaster-network:
    driver: bridge

